[General]
loglevel = notify
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://1.1.1.1/generate_204
test-timeout = 5
dns-server = 223.5.5.5, 119.29.29.29
encrypted-dns-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query
hijack-dns = *:53
udp-policy-not-supported-behaviour = REJECT
udp-priority = false
geoip-maxmind-url = https://github.com/Repcz/Tool/raw/X/GeoIP/CN.mmdb

[Proxy]

[Proxy Group]
𝗣𝗿𝗼𝘅𝘆 = select, no-alert=0, hidden=0, include-all-proxies=1, icon-url=B1::Logos::Microsoft Edge
𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺 = smart, no-alert=1, hidden=1, persistent=1, icon-url=B1::Logos::Telegram App
𝗔𝗜 = fallback, hidden=1, no-alert=1, icon-url=B1::Logos::ChatGPT
𝗔𝗽𝗽𝗹𝗲!𝗖𝗡 = smart, no-alert=0, hidden=1, icon-url=B1::Plants::Bitten Apple
𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸 = fallback, hidden=1, no-alert=1, icon-url=B1::Messaging::Delete Link
𝗙𝗶𝗻𝗮𝗹 = fallback, 𝗣𝗿𝗼𝘅𝘆, 𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸, DIRECT, no-alert=1, hidden=1, icon-url=B1::Industry::Broken Robot

[Rule]
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Direct.list,DIRECT
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Reject.list,REJECT,pre-matching
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Google.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Github.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Microsoft.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/AI.list,𝗔𝗜
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Telegram.list,𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Twitter.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/Proxy.list,𝗣𝗿𝗼𝘅𝘆
RULE-SET,https://github.com/Repcz/Tool/raw/X/Surge/Rules/AppleServers.list,𝗔𝗽𝗽𝗹𝗲!𝗖𝗡
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,𝗙𝗶𝗻𝗮𝗹

[MITM]
h2 = true

[MTProto]
interface = 127.0.0.1
port = 2887
secret = dd26d1e7523936deb5c47ad16b31fb0719
ipv6 = true
dc-config-url = https://github.com/Repcz/Tool/raw/X/Surge/mtproto-dc-config.json